### ISSUE TITLE
Cannot run examples following instructions in readme

### ISSUE THREAD

**Issue by yorodm** [nativeshell/examples#2]
The examples project fails to build:

Relevant output from cargo run:
```txt
External Tool Failed!
  Status: ExitStatus(ExitStatus(16896))
  Command: "\"flutter\" \"pub\" \"get\""
  Stderr:
  Because nativeshell_examples depends on nativeshell from path 
   which doesn't exist (could not find package nativeshell at "../nativeshell/nativeshell_dart"),
   version solving failed.
   pub get failed (66; Because nativeshell_examples depends on nativeshell from path which
   doesn't exist (could not find package nativeshell at "../nativeshell/nativeshell_dart"), version solving failed.)

  Stdout:
  Running "flutter pub get" in examples...
```

Environment:
 
1. Flutter 2.3.0-17.0.pre.228 • channel master
2. rustc 1.52.1 (9bc8c42bb 2021-05-09) (stable)
3. Runnin in Manjaro Linux

**Comment by knopp** [comment]
Sorry about that, can you update the repository and try again? Looks like I accidentally commited relative path instead of package version.

**Comment by knopp** [comment]
Were you able to run the examples? Can this issue be closed?

**Comment by yorodm** [comment]
Yes, everything runs fine! Thanks!!
